'use client';

import React, { createContext, useContext, useState, useEffect, ReactNode } from 'react';

// Language data with native script icons
export const languages = [
    { code: 'en', name: 'English', nativeName: 'English', icon: 'A', color: '#3b82f6' },
    { code: 'hi', name: 'Hindi', nativeName: 'हिंदी', icon: 'ह', color: '#f59e0b' },
    { code: 'mr', name: 'Marathi', nativeName: 'मराठी', icon: 'म', color: '#ec4899' },
    { code: 'ta', name: 'Tamil', nativeName: 'தமிழ்', icon: 'த', color: '#2563eb' },
    { code: 'te', name: 'Telugu', nativeName: 'తెలుగు', icon: 'త', color: '#f97316' },
    { code: 'bn', name: 'Bengali', nativeName: 'বাংলা', icon: 'বা', color: '#22c55e' },
    { code: 'gu', name: 'Gujarati', nativeName: 'ગુજરાતી', icon: 'ગુ', color: '#06b6d4' },
    { code: 'kn', name: 'Kannada', nativeName: 'ಕನ್ನಡ', icon: 'ಕ', color: '#8b5cf6' },
    { code: 'ml', name: 'Malayalam', nativeName: 'മലയാളം', icon: 'മ', color: '#10b981' },
    { code: 'pa', name: 'Punjabi', nativeName: 'ਪੰਜਾਬੀ', icon: 'ਪੰ', color: '#ef4444' },
    { code: 'ur', name: 'Urdu', nativeName: 'اردو', icon: 'د', color: '#6366f1' },
];

// Translations for all supported languages
export const translations: Record<string, Record<string, string>> = {
    en: {
        // Settings Page
        settings: 'Settings',
        settingsDesc: 'Manage your account preferences and settings',
        appearance: 'Appearance',
        theme: 'Theme',
        themeDesc: 'Choose your preferred theme',
        light: 'Light',
        dark: 'Dark',
        system: 'System',
        fontSize: 'Font Size',
        fontSizeDesc: 'Adjust text size',
        small: 'Small',
        medium: 'Medium',
        large: 'Large',
        notifications: 'Notifications',
        pushNotifications: 'Push Notifications',
        pushNotificationsDesc: 'Receive push notifications',
        emailNotifications: 'Email Notifications',
        emailNotificationsDesc: 'Receive email updates',
        assignmentReminders: 'Assignment Reminders',
        assignmentRemindersDesc: 'Get reminded about due dates',
        privacy: 'Privacy',
        profileVisibility: 'Profile Visibility',
        profileVisibilityDesc: 'Who can see your profile',
        everyone: 'Everyone',
        classmatesOnly: 'Classmates Only',
        teachersOnly: 'Teachers Only',
        private: 'Private',
        showProgress: 'Show Learning Progress',
        showProgressDesc: 'Display progress to others',
        language: 'Language',
        languageRegion: 'Language & Region',
        selectLanguage: 'Select your preferred language',
        timeZone: 'Time Zone',
        timeZoneDesc: 'Set your time zone',
        saveChanges: 'Save Changes',
        languageSaved: 'Language preference saved!',
        // Dashboard
        goodMorning: 'Good Morning',
        readyToLearn: 'Ready to continue your learning journey today?',
        dailyGoals: 'Daily Learning Goals',
        viewAll: 'View All',
        weeklyPerformance: 'Weekly Performance',
        recommendedForYou: 'Recommended For You',
        seeAll: 'See All',
        learningStreak: 'Learning Streak',
        days: 'Days',
        keepItUp: "You're on fire! Keep it up",
        todaysTarget: "Today's Target",
        completed: 'Completed',
        subjectPerformance: 'Subject Performance',
        assignments: 'Assignments',
        estimatedTime: 'Est.',
        // AI Tutor
        aiTutor: 'EduAI Tutor',
        readyToHelp: 'Ready to help',
        offlineMode: 'Offline Mode',
        clear: 'Clear',
        hello: 'Hello',
        whatToLearn: 'What would you like to learn today?',
        askAnything: 'Ask me anything about your studies...',
        explainTopic: 'Explain a topic',
        solveProblem: 'Solve a problem',
        createNotes: 'Create notes',
        helpStudy: 'Help me study',
    },
    hi: {
        settings: 'सेटिंग्स',
        settingsDesc: 'अपनी खाता प्राथमिकताएं और सेटिंग्स प्रबंधित करें',
        appearance: 'दिखावट',
        theme: 'थीम',
        themeDesc: 'अपनी पसंदीदा थीम चुनें',
        light: 'लाइट',
        dark: 'डार्क',
        system: 'सिस्टम',
        fontSize: 'फ़ॉन्ट आकार',
        fontSizeDesc: 'टेक्स्ट का आकार समायोजित करें',
        small: 'छोटा',
        medium: 'मध्यम',
        large: 'बड़ा',
        notifications: 'सूचनाएं',
        pushNotifications: 'पुश नोटिफिकेशन',
        pushNotificationsDesc: 'पुश नोटिफिकेशन प्राप्त करें',
        emailNotifications: 'ईमेल सूचनाएं',
        emailNotificationsDesc: 'ईमेल अपडेट प्राप्त करें',
        assignmentReminders: 'असाइनमेंट रिमाइंडर',
        assignmentRemindersDesc: 'नियत तारीखों की याद दिलाएं',
        privacy: 'गोपनीयता',
        profileVisibility: 'प्रोफ़ाइल दृश्यता',
        profileVisibilityDesc: 'आपकी प्रोफ़ाइल कौन देख सकता है',
        everyone: 'सभी',
        classmatesOnly: 'केवल सहपाठी',
        teachersOnly: 'केवल शिक्षक',
        private: 'निजी',
        showProgress: 'सीखने की प्रगति दिखाएं',
        showProgressDesc: 'दूसरों को प्रगति प्रदर्शित करें',
        language: 'भाषा',
        languageRegion: 'भाषा और क्षेत्र',
        selectLanguage: 'अपनी पसंदीदा भाषा चुनें',
        timeZone: 'समय क्षेत्र',
        timeZoneDesc: 'अपना समय क्षेत्र सेट करें',
        saveChanges: 'परिवर्तन सहेजें',
        languageSaved: 'भाषा प्राथमिकता सहेजी गई!',
        goodMorning: 'सुप्रभात',
        readyToLearn: 'आज अपनी सीखने की यात्रा जारी रखने के लिए तैयार?',
        dailyGoals: 'दैनिक सीखने के लक्ष्य',
        viewAll: 'सभी देखें',
        weeklyPerformance: 'साप्ताहिक प्रदर्शन',
        recommendedForYou: 'आपके लिए अनुशंसित',
        seeAll: 'सभी देखें',
        learningStreak: 'लर्निंग स्ट्रीक',
        days: 'दिन',
        keepItUp: 'आप आग पर हैं! जारी रखें',
        todaysTarget: 'आज का लक्ष्य',
        completed: 'पूर्ण',
        subjectPerformance: 'विषय प्रदर्शन',
        assignments: 'असाइनमेंट',
        estimatedTime: 'अनु.',
        aiTutor: 'EduAI ट्यूटर',
        readyToHelp: 'मदद के लिए तैयार',
        offlineMode: 'ऑफ़लाइन मोड',
        clear: 'साफ़ करें',
        hello: 'नमस्ते',
        whatToLearn: 'आज आप क्या सीखना चाहेंगे?',
        askAnything: 'अपनी पढ़ाई के बारे में कुछ भी पूछें...',
        explainTopic: 'विषय समझाएं',
        solveProblem: 'समस्या हल करें',
        createNotes: 'नोट्स बनाएं',
        helpStudy: 'पढ़ाई में मदद करें',
    },
    mr: {
        settings: 'सेटिंग्ज',
        settingsDesc: 'तुमची खाते प्राधान्ये आणि सेटिंग्ज व्यवस्थापित करा',
        appearance: 'देखावा',
        theme: 'थीम',
        themeDesc: 'तुमची आवडती थीम निवडा',
        light: 'लाइट',
        dark: 'डार्क',
        system: 'सिस्टम',
        fontSize: 'फॉन्ट आकार',
        fontSizeDesc: 'मजकूर आकार समायोजित करा',
        small: 'लहान',
        medium: 'मध्यम',
        large: 'मोठा',
        notifications: 'सूचना',
        pushNotifications: 'पुश नोटिफिकेशन',
        pushNotificationsDesc: 'पुश नोटिफिकेशन मिळवा',
        emailNotifications: 'ईमेल सूचना',
        emailNotificationsDesc: 'ईमेल अपडेट मिळवा',
        assignmentReminders: 'असाइनमेंट रिमाइंडर',
        assignmentRemindersDesc: 'देय तारखांची आठवण करा',
        privacy: 'गोपनीयता',
        profileVisibility: 'प्रोफाइल दृश्यता',
        profileVisibilityDesc: 'तुमची प्रोफाइल कोण पाहू शकते',
        everyone: 'सर्वजण',
        classmatesOnly: 'फक्त वर्गमित्र',
        teachersOnly: 'फक्त शिक्षक',
        private: 'खाजगी',
        showProgress: 'शिकण्याची प्रगती दाखवा',
        showProgressDesc: 'इतरांना प्रगती प्रदर्शित करा',
        language: 'भाषा',
        languageRegion: 'भाषा आणि प्रदेश',
        selectLanguage: 'तुमची आवडती भाषा निवडा',
        timeZone: 'वेळ क्षेत्र',
        timeZoneDesc: 'तुमचे वेळ क्षेत्र सेट करा',
        saveChanges: 'बदल जतन करा',
        languageSaved: 'भाषा प्राधान्य जतन केले!',
        goodMorning: 'सुप्रभात',
        readyToLearn: 'आज तुमचा शिक्षण प्रवास सुरू ठेवण्यास तयार?',
        dailyGoals: 'दैनंदिन शिक्षण उद्दिष्टे',
        viewAll: 'सर्व पहा',
        weeklyPerformance: 'साप्ताहिक कामगिरी',
        recommendedForYou: 'तुमच्यासाठी शिफारस',
        seeAll: 'सर्व पहा',
        learningStreak: 'लर्निंग स्ट्रीक',
        days: 'दिवस',
        keepItUp: 'तुम्ही छान करत आहात! असेच चालू ठेवा',
        todaysTarget: 'आजचे लक्ष्य',
        completed: 'पूर्ण',
        subjectPerformance: 'विषय कामगिरी',
        assignments: 'असाइनमेंट',
        estimatedTime: 'अंदाजे',
        aiTutor: 'EduAI ट्यूटर',
        readyToHelp: 'मदतीसाठी तयार',
        offlineMode: 'ऑफलाइन मोड',
        clear: 'साफ करा',
        hello: 'नमस्कार',
        whatToLearn: 'आज तुम्ही काय शिकू इच्छिता?',
        askAnything: 'तुमच्या अभ्यासाबद्दल काहीही विचारा...',
        explainTopic: 'विषय समजावून सांगा',
        solveProblem: 'समस्या सोडवा',
        createNotes: 'नोट्स तयार करा',
        helpStudy: 'अभ्यासात मदत करा',
    },
    ta: {
        settings: 'அமைப்புகள்',
        settingsDesc: 'உங்கள் கணக்கு விருப்பங்களையும் அமைப்புகளையும் நிர்வகிக்கவும்',
        appearance: 'தோற்றம்',
        theme: 'தீம்',
        themeDesc: 'உங்கள் விருப்பமான தீமைத் தேர்ந்தெடுக்கவும்',
        light: 'லைட்',
        dark: 'டார்க்',
        system: 'சிஸ்டம்',
        fontSize: 'எழுத்து அளவு',
        fontSizeDesc: 'உரை அளவை சரிசெய்யவும்',
        small: 'சிறிய',
        medium: 'நடுத்தர',
        large: 'பெரிய',
        notifications: 'அறிவிப்புகள்',
        pushNotifications: 'புஷ் அறிவிப்புகள்',
        pushNotificationsDesc: 'புஷ் அறிவிப்புகளைப் பெறுங்கள்',
        emailNotifications: 'மின்னஞ்சல் அறிவிப்புகள்',
        emailNotificationsDesc: 'மின்னஞ்சல் புதுப்பிப்புகளைப் பெறுங்கள்',
        assignmentReminders: 'பணி நினைவூட்டல்கள்',
        assignmentRemindersDesc: 'காலக்கெடுவை நினைவூட்டுங்கள்',
        privacy: 'தனியுரிமை',
        profileVisibility: 'சுயவிவர தெரிவுநிலை',
        profileVisibilityDesc: 'உங்கள் சுயவிவரத்தை யார் பார்க்கலாம்',
        everyone: 'அனைவரும்',
        classmatesOnly: 'வகுப்புத் தோழர்கள் மட்டும்',
        teachersOnly: 'ஆசிரியர்கள் மட்டும்',
        private: 'தனிப்பட்டது',
        showProgress: 'கற்றல் முன்னேற்றத்தைக் காட்டு',
        showProgressDesc: 'மற்றவர்களுக்கு முன்னேற்றத்தைக் காட்டு',
        language: 'மொழி',
        languageRegion: 'மொழி மற்றும் பிராந்தியம்',
        selectLanguage: 'உங்கள் விருப்பமான மொழியைத் தேர்ந்தெடுக்கவும்',
        timeZone: 'நேர மண்டலம்',
        timeZoneDesc: 'உங்கள் நேர மண்டலத்தை அமைக்கவும்',
        saveChanges: 'மாற்றங்களைச் சேமி',
        languageSaved: 'மொழி விருப்பம் சேமிக்கப்பட்டது!',
        goodMorning: 'காலை வணக்கம்',
        readyToLearn: 'இன்று உங்கள் கற்றல் பயணத்தைத் தொடர தயாரா?',
        dailyGoals: 'தினசரி கற்றல் இலக்குகள்',
        viewAll: 'அனைத்தையும் காண்',
        weeklyPerformance: 'வாராந்திர செயல்திறன்',
        recommendedForYou: 'உங்களுக்கான பரிந்துரைகள்',
        seeAll: 'அனைத்தையும் பார்',
        learningStreak: 'லர்னிங் ஸ்ட்ரீக்',
        days: 'நாட்கள்',
        keepItUp: 'நீங்கள் அருமையாக செய்கிறீர்கள்! தொடருங்கள்',
        todaysTarget: 'இன்றைய இலக்கு',
        completed: 'முடிந்தது',
        subjectPerformance: 'பாட செயல்திறன்',
        assignments: 'பணிகள்',
        estimatedTime: 'தோராய',
        aiTutor: 'EduAI ஆசிரியர்',
        readyToHelp: 'உதவ தயார்',
        offlineMode: 'ஆஃப்லைன் பயன்முறை',
        clear: 'அழி',
        hello: 'வணக்கம்',
        whatToLearn: 'இன்று நீங்கள் என்ன கற்க விரும்புகிறீர்கள்?',
        askAnything: 'உங்கள் படிப்பு பற்றி எதையும் கேளுங்கள்...',
        explainTopic: 'தலைப்பை விளக்கு',
        solveProblem: 'சிக்கலைத் தீர்',
        createNotes: 'குறிப்புகளை உருவாக்கு',
        helpStudy: 'படிக்க உதவு',
    },
    te: {
        settings: 'సెట్టింగ్‌లు',
        settingsDesc: 'మీ ఖాతా ప్రాధాన్యతలు మరియు సెట్టింగ్‌లను నిర్వహించండి',
        appearance: 'రూపం',
        theme: 'థీమ్',
        themeDesc: 'మీకు ఇష్టమైన థీమ్‌ను ఎంచుకోండి',
        light: 'లైట్',
        dark: 'డార్క్',
        system: 'సిస్టమ్',
        fontSize: 'ఫాంట్ పరిమాణం',
        fontSizeDesc: 'టెక్స్ట్ పరిమాణాన్ని సర్దుబాటు చేయండి',
        small: 'చిన్న',
        medium: 'మధ్యస్థ',
        large: 'పెద్ద',
        notifications: 'నోటిఫికేషన్లు',
        pushNotifications: 'పుష్ నోటిఫికేషన్లు',
        pushNotificationsDesc: 'పుష్ నోటిఫికేషన్లు స్వీకరించండి',
        emailNotifications: 'ఇమెయిల్ నోటిఫికేషన్లు',
        emailNotificationsDesc: 'ఇమెయిల్ అప్‌డేట్‌లు స్వీకరించండి',
        assignmentReminders: 'అసైన్‌మెంట్ రిమైండర్లు',
        assignmentRemindersDesc: 'గడువు తేదీల గురించి గుర్తు చేయండి',
        privacy: 'గోప్యత',
        profileVisibility: 'ప్రొఫైల్ కనిపించడం',
        profileVisibilityDesc: 'మీ ప్రొఫైల్‌ను ఎవరు చూడగలరు',
        everyone: 'అందరూ',
        classmatesOnly: 'సహపాఠులు మాత్రమే',
        teachersOnly: 'ఉపాధ్యాయులు మాత్రమే',
        private: 'ప్రైవేట్',
        showProgress: 'నేర్చుకునే పురోగతిని చూపించు',
        showProgressDesc: 'ఇతరులకు పురోగతిని ప్రదర్శించు',
        language: 'భాష',
        languageRegion: 'భాష మరియు ప్రాంతం',
        selectLanguage: 'మీకు ఇష్టమైన భాషను ఎంచుకోండి',
        timeZone: 'సమయ మండలం',
        timeZoneDesc: 'మీ సమయ మండలాన్ని సెట్ చేయండి',
        saveChanges: 'మార్పులు సేవ్ చేయి',
        languageSaved: 'భాష ప్రాధాన్యత సేవ్ చేయబడింది!',
        goodMorning: 'శుభోదయం',
        readyToLearn: 'ఈరోజు మీ నేర్చుకునే ప్రయాణాన్ని కొనసాగించడానికి సిద్ధంగా ఉన్నారా?',
        dailyGoals: 'రోజువారీ నేర్చుకునే లక్ష్యాలు',
        viewAll: 'అన్నీ చూడు',
        weeklyPerformance: 'వారపు పనితీరు',
        recommendedForYou: 'మీ కోసం సిఫార్సులు',
        seeAll: 'అన్నీ చూడు',
        learningStreak: 'లెర్నింగ్ స్ట్రీక్',
        days: 'రోజులు',
        keepItUp: 'మీరు అద్భుతంగా చేస్తున్నారు! కొనసాగించండి',
        todaysTarget: 'నేటి లక్ష్యం',
        completed: 'పూర్తయింది',
        subjectPerformance: 'సబ్జెక్ట్ పనితీరు',
        assignments: 'అసైన్‌మెంట్లు',
        estimatedTime: 'అంచనా',
        aiTutor: 'EduAI ట్యూటర్',
        readyToHelp: 'సహాయానికి సిద్ధం',
        offlineMode: 'ఆఫ్‌లైన్ మోడ్',
        clear: 'క్లియర్',
        hello: 'హలో',
        whatToLearn: 'ఈరోజు మీరు ఏమి నేర్చుకోవాలనుకుంటున్నారు?',
        askAnything: 'మీ చదువు గురించి ఏదైనా అడగండి...',
        explainTopic: 'అంశాన్ని వివరించు',
        solveProblem: 'సమస్యను పరిష్కరించు',
        createNotes: 'నోట్స్ సృష్టించు',
        helpStudy: 'చదవడానికి సహాయం చేయి',
    },
    bn: {
        settings: 'সেটিংস',
        settingsDesc: 'আপনার অ্যাকাউন্ট পছন্দ এবং সেটিংস পরিচালনা করুন',
        appearance: 'চেহারা',
        theme: 'থিম',
        themeDesc: 'আপনার পছন্দের থিম বেছে নিন',
        light: 'লাইট',
        dark: 'ডার্ক',
        system: 'সিস্টেম',
        language: 'ভাষা',
        languageRegion: 'ভাষা এবং অঞ্চল',
        selectLanguage: 'আপনার পছন্দের ভাষা নির্বাচন করুন',
        saveChanges: 'পরিবর্তনগুলি সংরক্ষণ করুন',
        languageSaved: 'ভাষা পছন্দ সংরক্ষিত!',
        goodMorning: 'সুপ্রভাত',
        hello: 'হ্যালো',
        notifications: 'বিজ্ঞপ্তি',
        privacy: 'গোপনীয়তা',
        fontSize: 'ফন্ট সাইজ',
        fontSizeDesc: 'টেক্সট সাইজ সামঞ্জস্য করুন',
        small: 'ছোট',
        medium: 'মাঝারি',
        large: 'বড়',
    },
    gu: {
        settings: 'સેટિંગ્સ',
        settingsDesc: 'તમારી ખાતા પસંદગીઓ અને સેટિંગ્સ મેનેજ કરો',
        language: 'ભાષા',
        languageRegion: 'ભાષા અને પ્રદેશ',
        selectLanguage: 'તમારી પસંદગીની ભાષા પસંદ કરો',
        saveChanges: 'ફેરફારો સાચવો',
        languageSaved: 'ભાષા પસંદગી સાચવી!',
        goodMorning: 'સુપ્રભાત',
        hello: 'નમસ્તે',
    },
    kn: {
        settings: 'ಸೆಟ್ಟಿಂಗ್‌ಗಳು',
        settingsDesc: 'ನಿಮ್ಮ ಖಾತೆ ಆದ್ಯತೆಗಳು ಮತ್ತು ಸೆಟ್ಟಿಂಗ್‌ಗಳನ್ನು ನಿರ್ವಹಿಸಿ',
        language: 'ಭಾಷೆ',
        languageRegion: 'ಭಾಷೆ ಮತ್ತು ಪ್ರದೇಶ',
        selectLanguage: 'ನಿಮ್ಮ ಆದ್ಯತೆಯ ಭಾಷೆಯನ್ನು ಆಯ್ಕೆಮಾಡಿ',
        saveChanges: 'ಬದಲಾವಣೆಗಳನ್ನು ಉಳಿಸಿ',
        languageSaved: 'ಭಾಷಾ ಆದ್ಯತೆ ಉಳಿಸಲಾಗಿದೆ!',
        goodMorning: 'ಶುಭೋದಯ',
        hello: 'ನಮಸ್ಕಾರ',
    },
    ml: {
        settings: 'ക്രമീകരണങ്ങൾ',
        settingsDesc: 'നിങ്ങളുടെ അക്കൗണ്ട് മുൻഗണനകളും ക്രമീകരണങ്ങളും നിയന്ത്രിക്കുക',
        language: 'ഭാഷ',
        languageRegion: 'ഭാഷയും പ്രദേശവും',
        selectLanguage: 'നിങ്ങളുടെ ഇഷ്ടപ്പെട്ട ഭാഷ തിരഞ്ഞെടുക്കുക',
        saveChanges: 'മാറ്റങ്ങൾ സേവ് ചെയ്യുക',
        languageSaved: 'ഭാഷാ മുൻഗണന സേവ് ചെയ്തു!',
        goodMorning: 'സുപ്രഭാതം',
        hello: 'ഹലോ',
    },
    pa: {
        settings: 'ਸੈਟਿੰਗਾਂ',
        settingsDesc: 'ਆਪਣੇ ਖਾਤੇ ਦੀਆਂ ਤਰਜੀਹਾਂ ਅਤੇ ਸੈਟਿੰਗਾਂ ਪ੍ਰਬੰਧਿਤ ਕਰੋ',
        language: 'ਭਾਸ਼ਾ',
        languageRegion: 'ਭਾਸ਼ਾ ਅਤੇ ਖੇਤਰ',
        selectLanguage: 'ਆਪਣੀ ਤਰਜੀਹੀ ਭਾਸ਼ਾ ਚੁਣੋ',
        saveChanges: 'ਤਬਦੀਲੀਆਂ ਸੇਵ ਕਰੋ',
        languageSaved: 'ਭਾਸ਼ਾ ਤਰਜੀਹ ਸੇਵ ਕੀਤੀ ਗਈ!',
        goodMorning: 'ਸ਼ੁਭ ਸਵੇਰ',
        hello: 'ਸਤ ਸ੍ਰੀ ਅਕਾਲ',
    },
    ur: {
        settings: 'ترتیبات',
        settingsDesc: 'اپنے اکاؤنٹ کی ترجیحات اور ترتیبات کا نظم کریں',
        language: 'زبان',
        languageRegion: 'زبان اور علاقہ',
        selectLanguage: 'اپنی پسندیدہ زبان منتخب کریں',
        saveChanges: 'تبدیلیاں محفوظ کریں',
        languageSaved: 'زبان کی ترجیح محفوظ!',
        goodMorning: 'صبح بخیر',
        hello: 'السلام علیکم',
    },
};

// Get translation with fallback to English
export const getTranslation = (lang: string, key: string): string => {
    return translations[lang]?.[key] || translations['en']?.[key] || key;
};

// Context type
interface LanguageContextType {
    language: string;
    setLanguage: (lang: string) => void;
    t: (key: string) => string;
}

// Create context
const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

// Provider component
export function LanguageProvider({ children }: { children: ReactNode }) {
    const [language, setLanguageState] = useState('en');

    useEffect(() => {
        // Load saved language from localStorage
        const savedLang = localStorage.getItem('preferred-language');
        if (savedLang && translations[savedLang]) {
            setLanguageState(savedLang);
        }
    }, []);

    const setLanguage = (lang: string) => {
        setLanguageState(lang);
        localStorage.setItem('preferred-language', lang);
    };

    const t = (key: string) => getTranslation(language, key);

    return (
        <LanguageContext.Provider value={{ language, setLanguage, t }}>
            {children}
        </LanguageContext.Provider>
    );
}

// Hook to use language context
export function useLanguage() {
    const context = useContext(LanguageContext);
    if (context === undefined) {
        throw new Error('useLanguage must be used within a LanguageProvider');
    }
    return context;
}

export default LanguageContext;
